# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d3db51b7d1efc5df9657190841ba477d28a8a3216bb1fa6396e9f93cde48c0a282e6be8936a92b910b0eaa88a16f8c6e6645f43995c8e202bb6d1a1ec0271e

test:
  secret_key_base: 8445ce9123efe913eceea91973767a4e8a78d498615d81511e70b1f5e86f07f0e12f91af2d435c0bc8da3e96b481ea15a785d3af089734b0ffce0178705fdae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
